name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  backend_build:
    name: Backend - Build
    needs: backend_build_test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Ensure gradlew is executable
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew bootJar -x test --no-daemon

  backend_build_test:
    name: Backend - Build + Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Ensure gradlew is executable
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew bootJar -x test --no-daemon

      - name: Test
        run: ./gradlew test --no-daemon

  frontend_build:
    name: Frontend - Build
    needs: frontend_build_test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front/my-react-app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: front/my-react-app/package-lock.json

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

  frontend_build_test:
    name: Frontend - Build + Test
    needs: backend_build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front/my-react-app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: front/my-react-app/package-lock.json

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
